# -*- coding: utf-8 -*-
"""market_regime_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13odElbibH7UrQDn-ub_iQjOReaGlrN0o
"""

import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
from numba import njit

def retrieve_data(ticker, start_date, end_date):
    data = yf.download(ticker, start=start_date, end=end_date)
    return data

def get_returns(data):
    prices = data["Close"]
    # returns: logarithmic ratio of current versus previous prices
    returns = np.log(prices / prices.shift(1))
    # dropping the na values
    returns = returns.dropna()
    # flattening the array
    returns = returns.values.flatten()
    return returns

@njit
def generate_regime(returns, position, regime_size):

    # create regime
    # Correctly extract numerical values from the returns DataFrame slice
    current_regime = returns[position : position + regime_size].tolist()

    # store regime
    regimes.append(current_regime)

    # compute metrics
    current_mean = np.mean(current_regime)
    current_std = np.std(current_regime)

    # store metrics
    regimes_mean.append(current_mean)
    regimes_std.append(current_std)

    # update position
    new_position = position + regime_size

    return new_position

def signal(regime_mean, regime_std, remaining_window_mean, remaining_window_std, regime_len, window_len):
    epsilon = 1e-6

    # Combined standard error of the difference between two independent means
    pooled_se = np.sqrt((regime_std**2 / regime_len) + (remaining_window_std**2 / window_len)) + epsilon

    # Calculate absolute t-stat
    t_stat = abs(remaining_window_mean - regime_mean) / pooled_se

    # Map to [0,1] probability range using a simple hyperbolic tangent (tanh)
    # instead of exp() for cleaner hardware boundary convergence
    signal_strength = np.tanh(t_stat / 2.0)

    return signal_strength

def generate_window(returns,
                    position,
                    window_size,
                    window):

    current_residual_len = len(window)
    slots_to_fill = window_size - current_residual_len

    # If the window is already full, compute statistics and return
    if slots_to_fill <= 0:
        window_mean = np.mean(window)
        window_std  = np.std(window)
        return window, window_mean, window_std, position

    top_up_end_idx = position + slots_to_fill

    # Defensive guard for the end of the data array
    if top_up_end_idx > len(returns):
        slots_to_fill = len(returns) - position
        top_up_end_idx = len(returns)

    fresh_inputs = returns[position:top_up_end_idx]

    # Create a fresh container matching the exact size and format required
    updated_window = np.empty(window_size, dtype=returns.dtype)

    # Place the surviving residual values at the front slots
    updated_window[:current_residual_len] = window

    # Place the fresh inputs directly behind them into the empty slots
    updated_window[current_residual_len : current_residual_len + len(fresh_inputs)] = fresh_inputs

    # Advance the reading pointer position by exactly what was pulled
    position = top_up_end_idx

    # Compute your window statistics from the newly completed uniform array
    window_mean = np.mean(updated_window)
    window_std  = np.std(updated_window)

    return updated_window, window_mean, window_std, position

def refine_boundary(window,
                    regime_mean,
                    regime_std,
                    window_mean,
                    regime_len,
                    window_len,
                    boundary_threshold = 0.5):

    n = len(window)

    boundary_index = 0

    # -------------------------------------------------
    # LEFT TRIMMING PROCESS
    # -------------------------------------------------

    for i in range(n):

        # remaining section
        remaining_window = window[i:]

        # compute size of remaining window
        remaining_size = len(remaining_window)

        # compute stats of remaining window
        remaining_mean = np.sum(remaining_window)/n
        remaining_std = np.std(remaining_window)

        # compute signal of remaining window
        remaining_signal = signal(regime_mean, regime_std,remaining_mean,remaining_std,regime_len,window_len)

        # -------------------------------------------------
        # Strong drift detected
        # -------------------------------------------------

        if remaining_signal < boundary_threshold:
            boundary_index = i
            continue
        elif remaining_signal > boundary_threshold:
            break

    return boundary_index

def pipeline(ticker,
             start_date,
             end_date,
             regime_size=30,
             window_size=20,
             minimum_remaining=5,
             boundary_threshold=0.35):

    # -----------------------------
    # LOAD DATA
    # -----------------------------
    data = retrieve_data(ticker, start_date, end_date)
    returns = get_returns(data)

    position = 0
    regime_pos = 0

    regimes = []
    regimes_mean = []
    regimes_std = []

    window = np.empty(0, dtype=returns.dtype)

    # =========================================================
    # FIX: INITIAL REGIME SEED (CRITICAL - prevents IndexError)
    # =========================================================
    initial_regime = returns[:regime_size].tolist()

    regimes.append(initial_regime)
    regimes_mean.append(np.mean(initial_regime))
    regimes_std.append(np.std(initial_regime))

    position = regime_size
    regime_pos = regime_size

    # -----------------------------
    # STREAMING LOOP
    # -----------------------------
    while position < len(returns):

        if position + window_size > len(returns):
            break

        window, window_mean, window_std, position = generate_window(
            returns, position, window_size, window
        )

        # safety check (extra stability)
        if len(regimes_mean) == 0:
            raise ValueError("No regime initialized")

        boundary = refine_boundary(
            window,
            regimes_mean[-1],
            regimes_std[-1],
            window_mean,
            regime_size,
            window_size,
            boundary_threshold
        )

        regime_window = window[:boundary + 1]

        # -----------------------------
        # UPDATE CURRENT REGIME
        # -----------------------------
        regimes[-1].extend(regime_window.tolist())

        # update rolling stats (last 100 points only)
        active_tail = np.array(regimes[-1][-100:], dtype=returns.dtype)
        regimes_mean[-1] = np.mean(active_tail)
        regimes_std[-1] = np.std(active_tail)

        regime_pos += len(regime_window)

        # -----------------------------
        # NEW REGIME DECISION
        # -----------------------------
        if window_size - len(regime_window) > minimum_remaining:

            remainder_window = window[boundary + 1:]

            if len(remainder_window) > 0:

                regimes.append(remainder_window.tolist())
                regimes_mean.append(np.mean(remainder_window))
                regimes_std.append(np.std(remainder_window))

            window = np.empty(0, dtype=returns.dtype)

        else:
            window = window[boundary + 1:]

    return returns, regimes, regimes_mean, regimes_std, regime_pos

def visualize_market_regimes(returns, regimes, regimes_std):
    """
    Plots cumulative asset returns and color-codes the background
    by the identified regime's volatility standard deviation.
    """
    # --- SANITY CHECK PRINTS ---
    print(f"Total return data points: {len(returns)}")
    print(f"Total tracked regimes: {len(regimes)}")
    print(f"Total metrics in regimes_std: {len(regimes_std)}")

    if len(regimes) == 0 or len(returns) == 0:
        print("❌ Error: 'returns' or 'regimes' data is empty. Run your pipeline cell first!")
        return

    # 1. Reconstruct the full time series timeline
    cumulative_returns = np.cumsum(returns)
    total_points = len(returns)

    # Create the figure canvas explicitly
    fig, ax = plt.subplots(figsize=(15, 7))

    # 2. Plot underlying asset data line
    ax.plot(cumulative_returns, color='black', linewidth=1.5, label='Cumulative Log Returns', zorder=3)

    # 3. Setup color mapping metrics safely
    current_global_idx = 0
    min_std = min(regimes_std) if regimes_std else 0
    max_std = max(regimes_std) if regimes_std else 1
    std_range = max_std - min_std if max_std != min_std else 1

    # Updated to use modern matplotlib syntax to clear deprecation warnings
    cmap = plt.get_cmap('YlOrRd')

    # 4. Step through flat regimes and shade the background canvas
    for i, regime in enumerate(regimes):
        regime_len = len(regime)
        start_idx = current_global_idx
        end_idx = current_global_idx + regime_len

        # Guard rails to make sure index bounds stay inside the returns size
        if start_idx >= total_points:
            break
        if end_idx > total_points:
            end_idx = total_points

        # Calculate a normalized intensity score between 0 and 1 for this regime's volatility
        normalized_vol = (regimes_std[i] - min_std) / std_range if std_range != 0 else 0.5

        # Fetch the corresponding background color (with transparency alpha)
        bg_color = cmap(normalized_vol * 0.7 + 0.1)

        # Shade the background span for this specific regime's duration
        ax.axvspan(start_idx, end_idx, color=bg_color, alpha=0.4, zorder=1)

        # Draw a subtle vertical dashed line showing the exact break boundary point
        if i < len(regimes) - 1 and end_idx < total_points:
            ax.axvline(x=end_idx, color='gray', linestyle='--', alpha=0.3, linewidth=1, zorder=2)

        current_global_idx = end_idx

    # 5. Add professional styling and labels
    ax.set_title('Unsupervised Market Regime Segmentation Engine Output', fontsize=14, fontweight='bold', pad=15)
    ax.set_xlabel('Time Step (Ticks / Index Coordinates)', fontsize=12)
    ax.set_ylabel('Cumulative Performance', fontsize=12)
    ax.set_xlim(0, total_points)
    ax.grid(True, linestyle=':', alpha=0.5, zorder=0)

    # Add a colorbar legend to decode the background shading intensity
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=plt.Normalize(vmax=max_std, vmin=min_std))
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, pad=0.02)

    # Added raw string 'r' prefix to completely eliminate the '\s' syntax warning
    cbar.set_label(r'Regime Volatility ($\sigma$ Status)', rotation=270, labelpad=15, fontsize=11)

    ax.legend(loc='upper left', frameon=True, facecolor='white', edgecolor='none')
    plt.tight_layout()

    # Force drawing/rendering commands explicitly
    plt.draw()
    plt.show()

tickers = ["GOOGL", "META", "TSLA"]
start_date="2015-01-01"
end_date="2024-01-01"
for t in tickers:
    returns, regimes, regimes_mean, regimes_std, regime_pos = pipeline(t, start_date, end_date)
    visualize_market_regimes(returns, regimes, regimes_std)